name: autodoc-generation
#triggers
on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Create virtual environment
      run: python -m venv venv && source venv/bin/activate && pip install -r requirements.txt
    - name: Create documentation
      run: cd docs && source ../venv/bin/activate && python ../venv/bin/sphinx-apidoc -f -d 8 -o . .. && make html && cd ..
    - name: Publish documentation to gh-pages branch
      run: |
        git config user.name 'github-actions[bot]' && git config user.email 'github-actions[bot]@users.noreply.github.com'
        mkdocs gh-deploy --config-file docs/mkdocs.yml --force
